"""Extract the approved layout without bundling its personal/transaction data.

Usage: python scripts/prepare-risti-template.py path/to/approved.xlsx
Styles, image, drawing, row/column dimensions, merges and page settings are
retained verbatim. Only input values and document history are removed.
"""
import base64
import hashlib
import json
import re
import sys
import zipfile
from pathlib import Path
import xml.etree.ElementTree as ET

source = Path(sys.argv[1])
root = Path(__file__).resolve().parent.parent
ns = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
fixed = set('A1 A6 H6 J6 A7 A8 A9 A11 F11 H11 J11 A12 A16 E16 I16 A17 A18 B18 E18 F18 G18 H18 I18 J18 K18 B19 C19 D19 A33 A34 A35 D35 E35 F35 A36 B36 C36 C47 A49 C49 A50 A51 D51 A52 A53 A54 A58 F58 J58 A59 A60'.split())
with zipfile.ZipFile(source) as archive:
    files = {name: archive.read(name) for name in archive.namelist()}

shared = files['xl/sharedStrings.xml'].decode('utf-8')
strings = re.findall(r'<si(?:\s[^>]*)?>.*?</si>', shared, re.S)
retained = []
mapping = {}

def sanitize_sheet(data, allowed):
    def replace(match):
        raw = match.group(0)
        ref = re.search(r'\br="([A-Z]+\d+)"', raw).group(1)
        if ref in allowed:
            if 't="s"' in raw:
                old = int(re.search(r'<v>(\d+)</v>', raw).group(1))
                if old not in mapping:
                    mapping[old] = len(retained)
                    retained.append(strings[old])
                raw = re.sub(r'<v>\d+</v>', f'<v>{mapping[old]}</v>', raw)
            return raw
        attributes = re.match(r'<c\b([^>]*?)(?:/?>)', raw).group(1).rstrip('/')
        attributes = re.sub(r'\s+(?:t|cm|vm)="[^"]*"', '', attributes)
        return f'<c{attributes}/>'
    return re.sub(r'<c\b[^>]*?(?:/>|>.*?</c>)', replace, data.decode('utf-8'), flags=re.S).encode('utf-8')

files['xl/worksheets/sheet1.xml'] = sanitize_sheet(files['xl/worksheets/sheet1.xml'], fixed)
files['xl/worksheets/sheet2.xml'] = sanitize_sheet(files['xl/worksheets/sheet2.xml'], set())
count = len(re.findall(r't="s"', files['xl/worksheets/sheet1.xml'].decode()))
files['xl/sharedStrings.xml'] = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    f'<sst xmlns="{ns["s"]}" count="{count}" uniqueCount="{len(retained)}">'
    + ''.join(retained) + '</sst>').encode('utf-8')

removed = {name for name in files if name.startswith(('docProps/', 'xl/persons/')) or name in {'xl/metadata', 'xl/calcChain.xml'}}
for name in removed:
    del files[name]
types = files['[Content_Types].xml'].decode('utf-8')
types = re.sub(r'<Override\b[^>]*/>', lambda m: '' if re.search(r'PartName="([^"]+)"', m[0]).group(1).lstrip('/') in removed else m[0], types)
files['[Content_Types].xml'] = types.encode('utf-8')
relations = files['xl/_rels/workbook.xml.rels'].decode('utf-8')
relations = re.sub(r'<Relationship\b[^>]*/>', lambda m: '' if re.search(r'Target="([^"]+)"', m[0]).group(1) in {'metadata', 'calcChain.xml', 'persons/person.xml'} else m[0], relations)
files['xl/_rels/workbook.xml.rels'] = relations.encode('utf-8')
files['_rels/.rels'] = b'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'
workbook = files['xl/workbook.xml'].decode('utf-8')
workbook = re.sub(r'<mc:AlternateContent\b.*?</mc:AlternateContent>|<xr:revisionPtr\b[^>]*/>|<extLst>.*?</extLst>', '', workbook, flags=re.S)
workbook = re.sub(r'<calcPr\b[^>]*/>', '<definedNames><definedName name="_xlnm.Print_Area" localSheetId="0">\'QQ\'!$A$1:$K$60</definedName></definedNames><calcPr calcId="191028" fullCalcOnLoad="1"/>', workbook)
files['xl/workbook.xml'] = workbook.encode('utf-8')

# Parse every XML part before emitting browser-ready, immutable template data.
for name, data in files.items():
    if name.endswith(('.xml', '.rels')):
        ET.fromstring(data)
payload = {name: base64.b64encode(data).decode('ascii') for name, data in files.items()}
(root / 'risti-template.js').write_text('// Approved RISTI workbook layout. Generated by scripts/prepare-risti-template.py.\n'
    + 'const RISTI_TEMPLATE = Object.freeze(' + json.dumps(payload, separators=(',', ':')) + ');\n', encoding='utf-8')
fingerprints = {name: hashlib.sha256(data).hexdigest() for name, data in files.items() if name in {'xl/styles.xml', 'xl/theme/theme1.xml', 'xl/media/image1.png', 'xl/drawings/drawing1.xml'}}
(root / 'tests/risti-template-fingerprints.json').write_text(json.dumps(fingerprints, indent=2) + '\n', encoding='utf-8')
print(f'Prepared {len(files)} template parts; original styles and logo preserved.')
